version: "3.0"
services:
  certimate:
    build: ../
    image: registry.cn-hangzhou.aliyuncs.com/hugobee/certimate:latest
    container_name: certimate_server
    ports:
      - 8090:8090
    volumes:
      - ./data:/app/pb_data
    restart: unless-stopped
